### ISSUE TITLE
data

### ISSUE THREAD

**Issue by wk199** [williamg42/IMU-GPS-Fusion#1]
hi,thank for sharing code.
Would you offer some data of the devices you use , so that we learn it well. 
thank you

**Comment by williamg42** [comment]
I am not quite sure what you mean by data of the devices I used. The particle filter as it stands pulls data from a BNO055 IMU sensor communicating over i2c, and talks to a gpsdaemon to get the devices current location.

**Comment by wk199** [comment]
Thank you for your reply. I know this project is running on live data from device. I donnot have data with imu and gps, so it's a problem to study it. If you have data recorded by your device, I can modify this project to read data from file offline to learn it. If donnot have, also thank you for sharing data.

**Comment by SHANTANUB009** [comment]
I am using an Arduino Pro mini and BNO080 to read data over i2c. I am getting quaternions. I am not sure how to use ur library in my arduino code . Can you please help me out!

**Comment by williamg42** [comment]
The code is not ardunio compatible.
